### ISSUE TITLE
Feature: Get video object by plex "key" identifier

### ISSUE THREAD

**Issue by simonwjackson** [mjs7231/plexapi#4] opened 2015-05-29 11:16 UTC
Its a bit more direct than having to identify a video by a query string (especially when looking for an episode of a tv series)

re #2

**Comment by mjs7231** [comment] 2015-05-29 14:44
Is this a duplicate of issue #2?

**Closed** 2015-05-29 14:46 UTC

**Comment by simonwjackson** [comment] 2015-05-29 15:10
Oh, no its not. Just misread it.
